<template>
    <!-- Generated Reports Table for Current Category -->
    <div class="w-full">
        <!-- Filter Bar -->
        <div class="bg-white rounded-lg border border-gray-200 p-4 flex gap-3 mb-4">
            <input
                v-model="searchQuery"
                type="text"
                placeholder="Search reports..."
                class="flex-1 px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#0c8ce9]"
            />
            <select
                v-model="statusFilter"
                class="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#0c8ce9]"
            >
                <option value="">All Status</option>
                <option value="completed">Completed</option>
                <option value="failed">Failed</option>
            </select>
            <button
                @click="clearFilters"
                class="px-3 py-2 text-sm text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
                Clear
            </button>
        </div>

        <!-- Reports Table -->
        <div class="bg-white rounded-lg border border-gray-200 overflow-hidden">
            <div class="overflow-x-auto">
                <table class="w-full">
                    <thead class="bg-gray-50 border-b border-gray-200 sticky top-0">
                        <tr>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wide">Report Name</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wide">Date Range</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wide">Department(s)</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wide">Generated Date</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wide">Generated By</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wide">Status</th>
                            <th class="px-6 py-3 text-left text-xs font-semibold text-gray-700 uppercase tracking-wide">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr
                            v-for="report in paginatedReports"
                            :key="report.id"
                            class="border-b border-gray-100 hover:bg-gray-50 transition-colors"
                        >
                            <td class="px-6 py-4 text-sm font-semibold text-gray-900">{{ report.name }}</td>
                            <td class="px-6 py-4 text-sm text-gray-600">{{ report.dateRange.start }} to {{ report.dateRange.end }}</td>
                            <td class="px-6 py-4 text-sm text-gray-600">{{ report.departments.join(', ') }}</td>
                            <td class="px-6 py-4 text-sm text-gray-600">{{ report.generatedDate }}</td>
                            <td class="px-6 py-4 text-sm text-gray-600">{{ report.generatedBy }}</td>
                            <td class="px-6 py-4 text-sm">
                                <span
                                    :class="[
                                        'inline-block px-3 py-1 rounded-full text-xs font-semibold',
                                        report.status === 'completed'
                                            ? 'bg-green-100 text-green-800'
                                            : 'bg-red-100 text-red-800'
                                    ]"
                                >
                                    {{ report.status.charAt(0).toUpperCase() + report.status.slice(1) }}
                                </span>
                            </td>
                            <td class="px-6 py-4 text-sm">
                                <div class="flex items-center gap-2">
                                    <button
                                        @click="viewReport(report)"
                                        class="text-blue-600 hover:text-blue-800 font-medium transition-colors"
                                    >
                                        View
                                    </button>
                                    <button
                                        @click="downloadReport(report)"
                                        class="text-green-600 hover:text-green-800 font-medium transition-colors"
                                    >
                                        Download
                                    </button>
                                    <button
                                        @click="printReport(report)"
                                        class="text-gray-600 hover:text-gray-800 font-medium transition-colors"
                                    >
                                        Print
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- Pagination -->
            <div class="px-6 py-4 bg-gray-50 border-t border-gray-200 flex justify-between items-center">
                <span class="text-sm font-semibold text-gray-800">
                    Total Reports: <span class="text-[#0c8ce9]">{{ categoryReports.length }}</span>
                </span>
                <div class="flex items-center gap-2">
                    <button
                        @click="previousPage"
                        :disabled="currentPage === 1"
                        class="px-3 py-2 text-sm border border-gray-300 rounded-lg hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                    >
                        Previous
                    </button>
                    <div class="flex items-center gap-1">
                        <button
                            v-for="page in pageNumbers"
                            :key="page"
                            @click="currentPage = page"
                            :class="[
                                'px-3 py-2 text-sm border rounded-lg transition-colors',
                                page === currentPage
                                    ? 'bg-[#0c8ce9] text-white border-[#0c8ce9]'
                                    : 'border-gray-300 hover:bg-gray-100'
                            ]"
                        >
                            {{ page }}
                        </button>
                    </div>
                    <button
                        @click="nextPage"
                        :disabled="currentPage === totalPages"
                        class="px-3 py-2 text-sm border border-gray-300 rounded-lg hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                    >
                        Next
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()
const props = defineProps({
    category: {
        type: String,
        required: true
    }
})

const searchQuery = ref('')
const statusFilter = ref('')
const currentPage = ref(1)
const itemsPerPage = 10

// Mock data - generated reports across all categories
const allReports = ref([
    {
        id: 1,
        name: 'Attendance Summary - March 2024',
        category: 'Attendance',
        dateRange: { start: '2024-03-01', end: '2024-03-31' },
        departments: ['IT', 'HR'],
        generatedDate: '2024-04-01',
        generatedBy: 'Admin User',
        status: 'completed'
    },
    {
        id: 2,
        name: 'Attendance Summary - February 2024',
        category: 'Attendance',
        dateRange: { start: '2024-02-01', end: '2024-02-29' },
        departments: ['Finance'],
        generatedDate: '2024-03-01',
        generatedBy: 'HR Manager',
        status: 'completed'
    },
    {
        id: 3,
        name: 'Mobilization Report Q1 2024',
        category: 'Mobilization',
        dateRange: { start: '2024-01-01', end: '2024-03-31' },
        departments: ['Operations', 'IT'],
        generatedDate: '2024-04-02',
        generatedBy: 'Operations Manager',
        status: 'completed'
    },
    {
        id: 4,
        name: 'Disciplinary Actions - Q1',
        category: 'Disciplinary',
        dateRange: { start: '2024-01-01', end: '2024-03-31' },
        departments: ['HR'],
        generatedDate: '2024-04-03',
        generatedBy: 'HR Director',
        status: 'completed'
    },
    {
        id: 5,
        name: 'Leave & Absence - March 2024',
        category: 'Leave & Absence',
        dateRange: { start: '2024-03-01', end: '2024-03-31' },
        departments: ['IT', 'Finance', 'HR'],
        generatedDate: '2024-04-04',
        generatedBy: 'HR Manager',
        status: 'completed'
    },
    {
        id: 6,
        name: 'Payroll Summary - March 2024',
        category: 'Payroll',
        dateRange: { start: '2024-03-01', end: '2024-03-31' },
        departments: ['Finance'],
        generatedDate: '2024-04-05',
        generatedBy: 'Finance Manager',
        status: 'completed'
    },
    {
        id: 7,
        name: 'System Audit Log - Q1 2024',
        category: 'Other System Reports',
        dateRange: { start: '2024-01-01', end: '2024-03-31' },
        departments: ['IT'],
        generatedDate: '2024-04-06',
        generatedBy: 'System Admin',
        status: 'completed'
    },
    {
        id: 8,
        name: 'Attendance Summary - April 2024',
        category: 'Attendance',
        dateRange: { start: '2024-04-01', end: '2024-04-15' },
        departments: ['IT'],
        generatedDate: '2024-04-15',
        generatedBy: 'Admin User',
        status: 'completed'
    },
    {
        id: 9,
        name: 'Leave & Absence - April 2024',
        category: 'Leave & Absence',
        dateRange: { start: '2024-04-01', end: '2024-04-30' },
        departments: ['HR'],
        generatedDate: '2024-04-10',
        generatedBy: 'HR Manager',
        status: 'completed'
    },
    {
        id: 10,
        name: 'Payroll Summary - April 2024',
        category: 'Payroll',
        dateRange: { start: '2024-04-01', end: '2024-04-30' },
        departments: ['Finance'],
        generatedDate: '2024-04-14',
        generatedBy: 'Finance Manager',
        status: 'completed'
    }
])

// Computed properties
const categoryReports = computed(() => {
    return allReports.value.filter(r => r.category === props.category)
})

const filteredReports = computed(() => {
    return categoryReports.value.filter(report => {
        const searchMatch = report.name.toLowerCase().includes(searchQuery.value.toLowerCase())
        const statusMatch = !statusFilter.value || report.status === statusFilter.value
        return searchMatch && statusMatch
    })
})

const totalPages = computed(() => {
    return Math.ceil(filteredReports.value.length / itemsPerPage)
})

const pageNumbers = computed(() => {
    const pages = []
    for (let i = 1; i <= Math.min(totalPages.value, 5); i++) {
        pages.push(i)
    }
    return pages
})

const paginatedReports = computed(() => {
    const start = (currentPage.value - 1) * itemsPerPage
    const end = start + itemsPerPage
    return filteredReports.value.slice(start, end)
})

// Methods
const clearFilters = () => {
    searchQuery.value = ''
    statusFilter.value = ''
    currentPage.value = 1
}

const viewReport = (report) => {
    // Store report data in sessionStorage for the preview page
    sessionStorage.setItem('currentReportData', JSON.stringify(report))
    // Navigate to preview
    router.push({ name: 'hr_report_preview', params: { reportId: report.id } })
}

const downloadReport = (report) => {
    // API call: GET /reports/download/:reportId
    console.log('Downloading report:', report.id)
    alert(`Downloading ${report.name}...`)
}

const printReport = (report) => {
    // API call: GET /reports/print/:reportId
    console.log('Printing report:', report.id)
    alert(`Printing ${report.name}...`)
}

const previousPage = () => {
    if (currentPage.value > 1) {
        currentPage.value--
    }
}

const nextPage = () => {
    if (currentPage.value < totalPages.value) {
        currentPage.value++
    }
}
</script>
